services:
  meusetup:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - hmac_key
    ports:
      - "8080:8080"
    restart: unless-stopped

secrets:
  hmac_key:
    file: ./hmac.key
